// <auto-generated />
using System;
using IoTSensorMonitoring.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IoTSensorMonitoring.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IoTSensorMonitoring.Domain.Entities.AlertHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlertRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("alert_rule_id");

                    b.Property<bool>("IsResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_resolved");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("triggered_at");

                    b.Property<decimal>("TriggeredValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("triggered_value");

                    b.HasKey("Id");

                    b.HasIndex("AlertRuleId");

                    b.HasIndex("IsResolved");

                    b.HasIndex("SensorId", "TriggeredAt");

                    b.ToTable("alert_history", (string)null);
                });

            modelBuilder.Entity("IoTSensorMonitoring.Domain.Entities.AlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("metric");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("comparison_operator");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("severity");

                    b.Property<decimal>("Threshold")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("threshold");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.ToTable("alert_rules", (string)null);
                });

            modelBuilder.Entity("IoTSensorMonitoring.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("contact_email");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("GrafanaOrgId")
                        .HasColumnType("integer")
                        .HasColumnName("grafana_org_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("IoTSensorMonitoring.Domain.Entities.DeviceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("CalibrationPeriodDays")
                        .HasColumnType("integer")
                        .HasColumnName("calibration_period_days");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_number");

                    b.Property<string>("SupportedMetrics")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("supported_metrics");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("IX_device_models_company_id");

                    b.HasIndex("CompanyId", "Manufacturer", "ModelNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_device_models_company_id_manufacturer_model_number");

                    b.ToTable("device_models", (string)null);
                });

            modelBuilder.Entity("IoTSensorMonitoring.Domain.Entities.Facility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<int>("FloorCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("floor_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("facilities", (string)null);
                });

            modelBuilder.Entity("IoTSensorMonitoring.Domain.Entities.MaintenanceLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("action_type");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("NextDueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_due_date");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.HasKey("Id");

                    b.HasIndex("NextDueDate");

                    b.HasIndex("SensorId");

                    b.ToTable("maintenance_logs", (string)null);
                });

            modelBuilder.Entity("IoTSensorMonitoring.Domain.Entities.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_model_id");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("firmware_version");

                    b.Property<DateTime?>("LastCalibrationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_calibration_date");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("mac_address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.HasIndex("DeviceModelId");

                    b.HasIndex("MacAddress")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("ZoneId");

                    b.ToTable("sensors", (string)null);
                });

            modelBuilder.Entity("IoTSensorMonitoring.Domain.Entities.SensorMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("BatteryLevel")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("battery_level");

                    b.Property<decimal?>("Humidity")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("humidity");

                    b.Property<DateTime>("MeasurementDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measurement_date");

                    b.Property<decimal?>("Pressure")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("pressure");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<int?>("SignalStrength")
                        .HasColumnType("integer")
                        .HasColumnName("signal_strength");

                    b.Property<decimal?>("Temperature")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("temperature");

                    b.HasKey("Id");

                    b.HasIndex("SensorId", "MeasurementDate");

                    b.ToTable("sensor_measurements", (string)null);
                });

            modelBuilder.Entity("IoTSensorMonitoring.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("IoTSensorMonitoring.Domain.Entities.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("facility_id");

                    b.Property<int>("FloorLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("floor_level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.ToTable("zones", (string)null);
                });

            modelBuilder.Entity("IoTSensorMonitoring.Domain.Entities.AlertHistory", b =>
                {
                    b.HasOne("IoTSensorMonitoring.Domain.Entities.AlertRule", "AlertRule")
                        .WithMany("AlertHistories")
                        .HasForeignKey("AlertRuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IoTSensorMonitoring.Domain.Entities.Sensor", "Sensor")
                        .WithMany("AlertHistories")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlertRule");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("IoTSensorMonitoring.Domain.Entities.AlertRule", b =>
                {
                    b.HasOne("IoTSensorMonitoring.Domain.Entities.Sensor", "Sensor")
                        .WithMany("AlertRules")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("IoTSensorMonitoring.Domain.Entities.DeviceModel", b =>
                {
                    b.HasOne("IoTSensorMonitoring.Domain.Entities.Company", "Company")
                        .WithMany("DeviceModels")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_device_models_companies_company_id")
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("IoTSensorMonitoring.Domain.Entities.Facility", b =>
                {
                    b.HasOne("IoTSensorMonitoring.Domain.Entities.Company", "Company")
                        .WithMany("Facilities")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("IoTSensorMonitoring.Domain.Entities.MaintenanceLog", b =>
                {
                    b.HasOne("IoTSensorMonitoring.Domain.Entities.Sensor", "Sensor")
                        .WithMany("MaintenanceLogs")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("IoTSensorMonitoring.Domain.Entities.Sensor", b =>
                {
                    b.HasOne("IoTSensorMonitoring.Domain.Entities.DeviceModel", "DeviceModel")
                        .WithMany("Sensors")
                        .HasForeignKey("DeviceModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IoTSensorMonitoring.Domain.Entities.Zone", "Zone")
                        .WithMany("Sensors")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeviceModel");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("IoTSensorMonitoring.Domain.Entities.SensorMeasurement", b =>
                {
                    b.HasOne("IoTSensorMonitoring.Domain.Entities.Sensor", "Sensor")
                        .WithMany("Measurements")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("IoTSensorMonitoring.Domain.Entities.User", b =>
                {
                    b.HasOne("IoTSensorMonitoring.Domain.Entities.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("IoTSensorMonitoring.Domain.Entities.Zone", b =>
                {
                    b.HasOne("IoTSensorMonitoring.Domain.Entities.Facility", "Facility")
                        .WithMany("Zones")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("IoTSensorMonitoring.Domain.Entities.AlertRule", b =>
                {
                    b.Navigation("AlertHistories");
                });

            modelBuilder.Entity("IoTSensorMonitoring.Domain.Entities.Company", b =>
                {
                    b.Navigation("DeviceModels");

                    b.Navigation("Facilities");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("IoTSensorMonitoring.Domain.Entities.DeviceModel", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("IoTSensorMonitoring.Domain.Entities.Facility", b =>
                {
                    b.Navigation("Zones");
                });

            modelBuilder.Entity("IoTSensorMonitoring.Domain.Entities.Sensor", b =>
                {
                    b.Navigation("AlertHistories");

                    b.Navigation("AlertRules");

                    b.Navigation("MaintenanceLogs");

                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("IoTSensorMonitoring.Domain.Entities.Zone", b =>
                {
                    b.Navigation("Sensors");
                });
#pragma warning restore 612, 618
        }
    }
}
