apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: iot
    isDefault: true
    editable: false
    jsonData:
      database: iot_sensor_monitoring
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: iot
